/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rockpaperscissors;

/**
 * This class is the data window that displays the backend information while the
 * program is running
 */
public class DataForm extends javax.swing.JFrame {

    static AgentModel stats = null;
    static Logic logic = null;
    static SimpleReflex simpleReflex = null;
    static RandomGuess randomGuess=null;

    /**
     * Creates new form DataForm
     *
     * @param incStats
     */
    public DataForm(Logic logc) {
        this.logic = logc;
        this.stats = logc.stats;
        this.simpleReflex = logc.simpleReflex;
        this.randomGuess = logc.randomGuess;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelNumTimesPicked = new javax.swing.JPanel();
        jLabelPickRock = new javax.swing.JLabel();
        jTextFieldPickRock = new javax.swing.JTextField();
        jTextFieldPickPaper = new javax.swing.JTextField();
        jLabelPickPaper = new javax.swing.JLabel();
        jTextFieldPickScissors = new javax.swing.JTextField();
        jLabelPickScissors = new javax.swing.JLabel();
        jLabelNumTimesPicked = new javax.swing.JLabel();
        jTextFieldPickRockAgent = new javax.swing.JTextField();
        jTextFieldPickPaperAgent = new javax.swing.JTextField();
        jTextFieldPickScissorsAgent = new javax.swing.JTextField();
        jLabelUser = new javax.swing.JLabel();
        jLabelAgent = new javax.swing.JLabel();
        jPanelAgentRanges = new javax.swing.JPanel();
        jLabelRangeRock = new javax.swing.JLabel();
        jTextFieldRangeRockLow = new javax.swing.JTextField();
        jTextFieldRangePaperLow = new javax.swing.JTextField();
        jLabelRangePaper = new javax.swing.JLabel();
        jTextFieldRangeScissorsLow = new javax.swing.JTextField();
        jLabelRangeScissors = new javax.swing.JLabel();
        jLabelAgentRanges = new javax.swing.JLabel();
        jTextFieldRangeRockHigh = new javax.swing.JTextField();
        jTextFieldRangePaperHigh = new javax.swing.JTextField();
        jTextFieldRangeScissorsHigh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextFieldPickRock1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPickRock2 = new javax.swing.JTextField();
        jLabelSimpleReflexLastChosen = new javax.swing.JLabel();
        jTextFieldSimpleAgentLastChosen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSimpleAgentTie = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabelRandom = new javax.swing.JLabel();
        jLabelRandomRight = new javax.swing.JLabel();
        jTextFieldRandomRight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRandomWrong = new javax.swing.JTextField();
        jTextFieldRandom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRandomTie = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agent's Data");

        jPanelNumTimesPicked.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPickRock.setText("Rock");

        jTextFieldPickRock.setEditable(false);
        jTextFieldPickRock.setText("0");

        jTextFieldPickPaper.setEditable(false);
        jTextFieldPickPaper.setText("0");

        jLabelPickPaper.setText("Paper");

        jTextFieldPickScissors.setEditable(false);
        jTextFieldPickScissors.setText("0");

        jLabelPickScissors.setText("Scissors");

        jLabelNumTimesPicked.setText("# of times picked");

        jTextFieldPickRockAgent.setEditable(false);
        jTextFieldPickRockAgent.setText("0");

        jTextFieldPickPaperAgent.setEditable(false);
        jTextFieldPickPaperAgent.setText("0");

        jTextFieldPickScissorsAgent.setEditable(false);
        jTextFieldPickScissorsAgent.setText("0");

        jLabelUser.setText("User");

        jLabelAgent.setText("Agent");

        javax.swing.GroupLayout jPanelNumTimesPickedLayout = new javax.swing.GroupLayout(jPanelNumTimesPicked);
        jPanelNumTimesPicked.setLayout(jPanelNumTimesPickedLayout);
        jPanelNumTimesPickedLayout.setHorizontalGroup(
            jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumTimesPickedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumTimesPicked)
                    .addGroup(jPanelNumTimesPickedLayout.createSequentialGroup()
                        .addGroup(jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNumTimesPickedLayout.createSequentialGroup()
                                .addComponent(jLabelPickPaper)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPickPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNumTimesPickedLayout.createSequentialGroup()
                                .addComponent(jLabelPickScissors)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPickScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelNumTimesPickedLayout.createSequentialGroup()
                                .addComponent(jLabelPickRock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUser)
                                    .addComponent(jTextFieldPickRock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPickRockAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPickPaperAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPickScissorsAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAgent))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanelNumTimesPickedLayout.setVerticalGroup(
            jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumTimesPickedLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelNumTimesPicked)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUser)
                    .addComponent(jLabelAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPickRock)
                    .addComponent(jTextFieldPickRock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPickRockAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPickPaper)
                    .addComponent(jTextFieldPickPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPickPaperAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumTimesPickedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPickScissors)
                    .addComponent(jTextFieldPickScissors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPickScissorsAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelAgentRanges.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelRangeRock.setText("Rock");

        jTextFieldRangeRockLow.setEditable(false);
        jTextFieldRangeRockLow.setText("0");

        jTextFieldRangePaperLow.setEditable(false);
        jTextFieldRangePaperLow.setText("0");

        jLabelRangePaper.setText("Paper");

        jTextFieldRangeScissorsLow.setEditable(false);
        jTextFieldRangeScissorsLow.setText("0");

        jLabelRangeScissors.setText("Scissors");

        jLabelAgentRanges.setText("Simple Reflex Agent Selection Ranges");

        jTextFieldRangeRockHigh.setEditable(false);
        jTextFieldRangeRockHigh.setText("0");

        jTextFieldRangePaperHigh.setEditable(false);
        jTextFieldRangePaperHigh.setText("0");

        jTextFieldRangeScissorsHigh.setEditable(false);
        jTextFieldRangeScissorsHigh.setText("0");

        jLabel2.setText("-");

        jLabel3.setText("-");

        jLabel4.setText("-");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("The above represents the likelihood\nthe computer thinks the player will\npick a certain choice.");
        jScrollPane2.setViewportView(jTextArea2);

        jTextFieldPickRock1.setEditable(false);
        jTextFieldPickRock1.setText("0");

        jLabel6.setText("Right");

        jLabel7.setText("Wrong");

        jTextFieldPickRock2.setEditable(false);
        jTextFieldPickRock2.setText("0");

        jLabelSimpleReflexLastChosen.setText("Last Chosen");

        jTextFieldSimpleAgentLastChosen.setEditable(false);
        jTextFieldSimpleAgentLastChosen.setText("0");

        jLabel5.setText("Tie");

        jTextFieldSimpleAgentTie.setEditable(false);
        jTextFieldSimpleAgentTie.setText("0");

        javax.swing.GroupLayout jPanelAgentRangesLayout = new javax.swing.GroupLayout(jPanelAgentRanges);
        jPanelAgentRanges.setLayout(jPanelAgentRangesLayout);
        jPanelAgentRangesLayout.setHorizontalGroup(
            jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgentRangesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgentRangesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAgentRangesLayout.createSequentialGroup()
                                .addComponent(jLabelRangeRock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldRangeRockLow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAgentRangesLayout.createSequentialGroup()
                                .addComponent(jLabelRangePaper)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldRangePaperLow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAgentRangesLayout.createSequentialGroup()
                                .addComponent(jLabelRangeScissors)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRangeScissorsLow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRangeRockHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRangePaperHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRangeScissorsHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAgentRangesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPickRock1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPickRock2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSimpleAgentTie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAgentRangesLayout.createSequentialGroup()
                        .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAgentRanges)
                            .addGroup(jPanelAgentRangesLayout.createSequentialGroup()
                                .addComponent(jLabelSimpleReflexLastChosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSimpleAgentLastChosen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAgentRangesLayout.setVerticalGroup(
            jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgentRangesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelAgentRanges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSimpleReflexLastChosen)
                    .addComponent(jTextFieldSimpleAgentLastChosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRangeRock)
                    .addComponent(jTextFieldRangeRockLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRangeRockHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRangePaper)
                    .addComponent(jTextFieldRangePaperLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRangePaperHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRangeScissors)
                    .addComponent(jTextFieldRangeScissorsLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRangeScissorsHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgentRangesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPickRock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPickRock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSimpleAgentTie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("The computer makes its choice based on the history of the player's\nchoices.\n\ni.e. if the player selects Rock the computer is more likely to\nselect Paper");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelRandom.setText("Random Guess Agent");

        jLabelRandomRight.setText("Right");

        jTextFieldRandomRight.setEditable(false);
        jTextFieldRandomRight.setText("0");

        jLabel9.setText("Wrong");

        jTextFieldRandomWrong.setEditable(false);
        jTextFieldRandomWrong.setText("0");

        jLabel10.setText("Tie");

        jTextFieldRandomTie.setEditable(false);
        jTextFieldRandomTie.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRandom)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelRandomRight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldRandomRight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRandomTie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRandomWrong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRandom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRandomRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRandomRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldRandomWrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldRandomTie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelNumTimesPicked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelAgentRanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelNumTimesPicked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelAgentRanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //update the fields of the window
    public void update() {
        updateSimpleReflex();
        updateRandom();
    }

    private void updateRandom() {
        jTextFieldRandom.setText("" +randomGuess.getLastChoice());
    }

    private void updateSimpleReflex() {
        jTextFieldSimpleAgentLastChosen.setText("" + ((float) simpleReflex.getChoice()));

        jTextFieldPickRock.setText("" + stats.getPickRock());
        jTextFieldPickPaper.setText("" + stats.getPickPaper());
        jTextFieldPickScissors.setText("" + stats.getPickScissors());

        jTextFieldPickRockAgent.setText("" + simpleReflex.getPickRockAgent());
        jTextFieldPickPaperAgent.setText("" + simpleReflex.getPickPaperAgent());
        jTextFieldPickScissorsAgent.setText("" + simpleReflex.getPickScissorsAgent());

        jTextFieldRangeRockLow.setText("0");//the bottom is always 0
        jTextFieldRangeRockHigh.setText("" + simpleReflex.getChosenRock());

        jTextFieldRangePaperLow.setText("" + simpleReflex.getChosenRock());
        jTextFieldRangePaperHigh.setText("" + simpleReflex.getChosenPaper());

        jTextFieldRangeScissorsLow.setText("" + simpleReflex.getChosenPaper());
        jTextFieldRangeScissorsHigh.setText("1");//the top is always 1
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataForm(logic).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAgent;
    private javax.swing.JLabel jLabelAgentRanges;
    private javax.swing.JLabel jLabelNumTimesPicked;
    private javax.swing.JLabel jLabelPickPaper;
    private javax.swing.JLabel jLabelPickRock;
    private javax.swing.JLabel jLabelPickScissors;
    private javax.swing.JLabel jLabelRandom;
    private javax.swing.JLabel jLabelRandomRight;
    private javax.swing.JLabel jLabelRangePaper;
    private javax.swing.JLabel jLabelRangeRock;
    private javax.swing.JLabel jLabelRangeScissors;
    private javax.swing.JLabel jLabelSimpleReflexLastChosen;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAgentRanges;
    private javax.swing.JPanel jPanelNumTimesPicked;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldPickPaper;
    private javax.swing.JTextField jTextFieldPickPaperAgent;
    private javax.swing.JTextField jTextFieldPickRock;
    private javax.swing.JTextField jTextFieldPickRock1;
    private javax.swing.JTextField jTextFieldPickRock2;
    private javax.swing.JTextField jTextFieldPickRockAgent;
    private javax.swing.JTextField jTextFieldPickScissors;
    private javax.swing.JTextField jTextFieldPickScissorsAgent;
    private javax.swing.JTextField jTextFieldRandom;
    private javax.swing.JTextField jTextFieldRandomRight;
    private javax.swing.JTextField jTextFieldRandomTie;
    private javax.swing.JTextField jTextFieldRandomWrong;
    private javax.swing.JTextField jTextFieldRangePaperHigh;
    private javax.swing.JTextField jTextFieldRangePaperLow;
    private javax.swing.JTextField jTextFieldRangeRockHigh;
    private javax.swing.JTextField jTextFieldRangeRockLow;
    private javax.swing.JTextField jTextFieldRangeScissorsHigh;
    private javax.swing.JTextField jTextFieldRangeScissorsLow;
    private javax.swing.JTextField jTextFieldSimpleAgentLastChosen;
    private javax.swing.JTextField jTextFieldSimpleAgentTie;
    // End of variables declaration//GEN-END:variables
}
