/**
 * Course: CS 4523
 * Student name: Erik Storla
 * Student ID: 000159035
 * Assignment #: 1
 * Due Date: 9/9/2014
 * Signature: ____________________
 * Score: ____________________
 */
package rockpaperscissors;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * A Rock, Paper, Scissors program
 *
 * While simple, the program represents a model-based reflex agent. The program
 * keeps track of the player's choice history and uses that to try adapt and
 * make more intelligent selections.
 */
public class Gui extends javax.swing.JFrame {

    AgentModel stats = new AgentModel();
    Logic logic = new Logic(stats);
    DataForm dataForm = new DataForm(logic);
    

    /**
     * Creates new form gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldWin = new javax.swing.JTextField();
        jTextFieldLoss = new javax.swing.JTextField();
        jTextFieldTie = new javax.swing.JTextField();
        jLabelWin = new javax.swing.JLabel();
        jLabelLoss = new javax.swing.JLabel();
        jLabelTie = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonRock = new javax.swing.JButton();
        jButtonPaper = new javax.swing.JButton();
        jButtonScissors = new javax.swing.JButton();
        jLabelChoose = new javax.swing.JLabel();
        jButtonAI = new javax.swing.JButton();
        jPanelResult = new javax.swing.JPanel();
        jLabelPlayerChose = new javax.swing.JLabel();
        jLabelAIChose = new javax.swing.JLabel();
        jTextFieldPlayerChose = new javax.swing.JTextField();
        jTextFieldAIChose = new javax.swing.JTextField();
        jLabelResult = new javax.swing.JLabel();
        jLabelSignature = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rock, Paper, Scissors");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldWin.setEditable(false);
        jTextFieldWin.setText("0");

        jTextFieldLoss.setEditable(false);
        jTextFieldLoss.setText("0");

        jTextFieldTie.setEditable(false);
        jTextFieldTie.setText("0");

        jLabelWin.setText("Win");

        jLabelLoss.setText("Loss");

        jLabelTie.setText("Tie");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelWin)
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldWin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelLoss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWin)
                    .addComponent(jTextFieldWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelLoss))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonRock.setText("Rock");
        jButtonRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRockActionPerformed(evt);
            }
        });

        jButtonPaper.setText("Paper");
        jButtonPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaperActionPerformed(evt);
            }
        });

        jButtonScissors.setText("Scissors");
        jButtonScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScissorsActionPerformed(evt);
            }
        });

        jLabelChoose.setText("Choose:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonRock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPaper)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonScissors))
                    .addComponent(jLabelChoose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelChoose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRock)
                    .addComponent(jButtonPaper)
                    .addComponent(jButtonScissors))
                .addContainerGap())
        );

        jButtonAI.setText("Show Data");
        jButtonAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAIActionPerformed(evt);
            }
        });

        jPanelResult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPlayerChose.setText("You chose:");

        jLabelAIChose.setText("Computer chose:");

        jTextFieldPlayerChose.setEditable(false);

        jTextFieldAIChose.setEditable(false);

        jLabelResult.setText("Result");

        javax.swing.GroupLayout jPanelResultLayout = new javax.swing.GroupLayout(jPanelResult);
        jPanelResult.setLayout(jPanelResultLayout);
        jPanelResultLayout.setHorizontalGroup(
            jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelResultLayout.createSequentialGroup()
                        .addGroup(jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlayerChose)
                            .addComponent(jTextFieldPlayerChose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAIChose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAIChose)))
                    .addComponent(jLabelResult))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelResultLayout.setVerticalGroup(
            jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlayerChose)
                    .addComponent(jLabelAIChose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPlayerChose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAIChose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelSignature.setForeground(new java.awt.Color(0, 51, 255));
        jLabelSignature.setText("estorla@spsu.edu");
        jLabelSignature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSignatureMouseClicked(evt);
            }
        });

        jLabel1.setText("By Erik Storla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSignature))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAI)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSignature)
                    .addComponent(jLabel1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRockActionPerformed
        clicked("rock");
    }//GEN-LAST:event_jButtonRockActionPerformed

    private void jButtonPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaperActionPerformed
        clicked("paper");
    }//GEN-LAST:event_jButtonPaperActionPerformed

    private void jButtonScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScissorsActionPerformed
        clicked("scissors");
    }//GEN-LAST:event_jButtonScissorsActionPerformed

    private void jButtonAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAIActionPerformed
        //this toggles displaying/hiding the window containing data
        dataForm.update();
        dataForm.setLocation(this.getX() + this.getWidth(), this.getY());
        dataForm.setVisible(!dataForm.isVisible());
    }//GEN-LAST:event_jButtonAIActionPerformed

    private void jLabelSignatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignatureMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("mailto:estorla@spsu.edu?subject=RPS"));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelSignatureMouseClicked

    private void clicked(String userChoice) {
        //String aiChoice = simpleReflex.agentGetChoice();//have the agent pick a choice
        String aiChoice = Logic.getChoice();
                
        //fill in the fields for what the player and computer selected
        jTextFieldPlayerChose.setText("" + userChoice);
        jTextFieldAIChose.setText("" + aiChoice);
        System.out.println("User: " + userChoice + "\tAI: " + aiChoice);

        //turn the Strings into ints for comparison
        int user = Logic.ChoiceStringToInt(userChoice);
        int ai = Logic.ChoiceStringToInt(aiChoice);

        String result = Logic.compareChoices(user, ai);//make the actual comparison

        //decide who won and update scores and data accordingly
        switch (result) {
            case "Tie":
                jLabelResult.setText("Tie!");
                stats.tie();
                break;
            case "User":
                jLabelResult.setText("You won!");
                stats.win();
                break;
            case "AI":
                jLabelResult.setText("I won!");
                stats.loss();
                break;
        }
        
        stats.picked(userChoice);
        logic.picked(userChoice);
        logic.update();
        updateScore();//update the GUI's stats
    }

    private void updateScore() {
        jTextFieldLoss.setText("" + stats.getLoss());
        jTextFieldTie.setText("" + stats.getTie());
        jTextFieldWin.setText("" + stats.getWin());

        dataForm.update();//update the stats on the data window
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAI;
    private javax.swing.JButton jButtonPaper;
    private javax.swing.JButton jButtonRock;
    private javax.swing.JButton jButtonScissors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAIChose;
    private javax.swing.JLabel jLabelChoose;
    private javax.swing.JLabel jLabelLoss;
    private javax.swing.JLabel jLabelPlayerChose;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelSignature;
    private javax.swing.JLabel jLabelTie;
    private javax.swing.JLabel jLabelWin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelResult;
    private javax.swing.JTextField jTextFieldAIChose;
    private javax.swing.JTextField jTextFieldLoss;
    private javax.swing.JTextField jTextFieldPlayerChose;
    private javax.swing.JTextField jTextFieldTie;
    private javax.swing.JTextField jTextFieldWin;
    // End of variables declaration//GEN-END:variables
}
